/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.AWTException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KIIT
 */
@SuppressWarnings("ALL")
public class TyperXFrame extends javax.swing.JFrame {

    public TyperXWorker worker;

    /**
     * Creates new form TyperXFrame
     *
     * @throws AWTException
     */
    public TyperXFrame() throws AWTException {
        worker = new TyperXWorker(this);
        initComponents();
        this.startUI();
    }

    public void startUI() {
        this.startTyping.setVisible(true);
        this.stopTyping.setVisible(false);
        this.lableInfo.setText("Ready for transfer");
        this.progress.setValue(0);
    }

    public void stopUI() {
        this.startTyping.setVisible(false);
        this.stopTyping.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        startTyping = new javax.swing.JButton();
        stopTyping = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lableInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        startTimerCombobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        strokeTimerComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        lineWrapCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TyperX");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        textArea.setPreferredSize(null);
        jScrollPane1.setViewportView(textArea);

        startTyping.setText("Start Typing");
        startTyping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTypingActionPerformed(evt);
            }
        });

        stopTyping.setText("Stop Typing");
        stopTyping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopTypingActionPerformed(evt);
            }
        });

        jLabel1.setText("v0.2 #CarryMinati");

        lableInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableInfo.setText("To kaisa hai app log ?");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome to TyperX v0.2 \nNote:- Dont use the system for anything else while TyperX is running.\n       Have patience,current transfer speed is 7.5k chars/Min.\nSteps to use TyperX:-\n1.Paste/Type  some Text in the space given below.\n2.Click on \"start typing\" button below. A 5 timer will start.\n3.Go to the target window where copy/paste is diabled and place the cursor there within that 5 seconds timer.\n4.Sit back and relax. After the timer end.TyperX will transfer all of the text to that window.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCaretPosition(0);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Timer duration (in Seconds)");

        startTimerCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", " " }));
        startTimerCombobox.setSelectedIndex(3);
        startTimerCombobox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startTimerComboboxPropertyChange(evt);
            }
        });

        jLabel3.setText("Key Stroke responce Time");

        strokeTimerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "4", "6", "8", "10", "12" }));
        strokeTimerComboBox.setSelectedIndex(3);
        strokeTimerComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                strokeTimerComboBoxPropertyChange(evt);
            }
        });

        jLabel4.setText("TyperX will wait for this many seconds before stating Transfer");

        jLabel5.setText("The time diffrence between each charecter transfer in milis");

        lineWrapCheckBox.setSelected(true);
        lineWrapCheckBox.setText("Word Wrap");
        lineWrapCheckBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lineWrapCheckBoxPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startTyping)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopTyping)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12))
                            .addComponent(lableInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startTimerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62)
                        .addComponent(lineWrapCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(strokeTimerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startTyping)
                            .addComponent(stopTyping)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lableInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(startTimerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lineWrapCheckBox))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(strokeTimerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTypingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTypingActionPerformed
        String text = this.textArea.getText();
        this.worker.startRequest(text);

    }//GEN-LAST:event_startTypingActionPerformed

    private void stopTypingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopTypingActionPerformed
        this.worker.stopRequest();

    }//GEN-LAST:event_stopTypingActionPerformed


    private void lineWrapCheckBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lineWrapCheckBoxPropertyChange

        this.textArea.setLineWrap(this.lineWrapCheckBox.isSelected());

    }//GEN-LAST:event_lineWrapCheckBoxPropertyChange

    private void startTimerComboboxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startTimerComboboxPropertyChange
        int value = Integer.parseInt(this.startTimerCombobox.getSelectedItem().toString());
        worker.setStartTime(value);

    }//GEN-LAST:event_startTimerComboboxPropertyChange

    private void strokeTimerComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_strokeTimerComboBoxPropertyChange

        int value = Integer.parseInt(strokeTimerComboBox.getSelectedItem().toString());
        worker.setKeyStrokeDelay(value);

    }//GEN-LAST:event_strokeTimerComboBoxPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TyperXFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                TyperXFrame frame = new TyperXFrame();
                frame.setAlwaysOnTop(true);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);

            } catch (AWTException ex) {
                Logger.getLogger(TyperXFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel lableInfo;
    public javax.swing.JCheckBox lineWrapCheckBox;
    public javax.swing.JProgressBar progress;
    public javax.swing.JComboBox startTimerCombobox;
    public javax.swing.JButton startTyping;
    public javax.swing.JButton stopTyping;
    public javax.swing.JComboBox strokeTimerComboBox;
    public javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
