/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author KIIT
 */
public class TyperXFrame extends javax.swing.JFrame
{

    Robot robot;
    boolean isRunning;

    void sendKeys(String keys)
    {
        Runnable run = () -> {
            isRunning = true;
            for (int i = 0; i < 5; i++) {
                this.lableInfo.setText("Starting typing in " + (5 - i) + " sec");
                try{
                    Thread.sleep(1000l);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TyperXFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            this.lableInfo.setText("Runnng now..");
            for (char c : keys.toCharArray()) {
                if (!isRunning) {
                    break;
                }
                try{
                    boolean isCap = java.lang.Character.isUpperCase(c);
                    int keyCode = KeyEvent.getExtendedKeyCodeForChar(c);
                    if (isCap) {
                        robot.keyPress(KeyEvent.VK_SHIFT);
                    }
                    robot.keyPress(keyCode);

                    robot.delay(4);
                    robot.keyRelease(keyCode);
                    robot.delay(4);
                    if (isCap) {
                        robot.keyRelease(KeyEvent.VK_SHIFT);
                    }
                } catch (Exception ex) {

                    Logger.getLogger(TyperXFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                this.lableInfo.setText("Cummon Nigga press start");

            }
        };
        Thread th = new Thread(run);
        th.start();
    }

    /**
     * Creates new form TyperXFrame
     */
    public TyperXFrame() throws AWTException
    {
        robot = new Robot();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        startTyping = new javax.swing.JButton();
        stopTyping = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lableInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Typer NX");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        startTyping.setText("Start Typing");
        startTyping.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startTypingActionPerformed(evt);
            }
        });

        stopTyping.setText("Stop Typing");
        stopTyping.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stopTypingActionPerformed(evt);
            }
        });

        jLabel1.setText("v0.1 #PKMB");

        lableInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableInfo.setText("Cummon Nigga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                              .addComponent(jScrollPane1)
                                                                              .addContainerGap())
                                                            .addGroup(layout.createSequentialGroup()
                                                                              .addComponent(startTyping)
                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                              .addComponent(stopTyping)
                                                                              .addGap(47, 47, 47)
                                                                              .addComponent(lableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                                                              .addComponent(jLabel1))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                              .addComponent(startTyping)
                                                                              .addComponent(stopTyping)
                                                                              .addComponent(lableInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                          .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void startTypingActionPerformed(java.awt.event.ActionEvent evt)
    {
        if (this.isRunning) {
            this.isRunning = false;
        }
        String text = this.textArea.getText();
        this.sendKeys(text);
    }

    private void stopTypingActionPerformed(java.awt.event.ActionEvent evt)
    {

        this.isRunning = false;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TyperXFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try{
                TyperXFrame frame = new TyperXFrame();
                frame.setAlwaysOnTop(true);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);

            } catch (AWTException ex) {
                Logger.getLogger(TyperXFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify
    public javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lableInfo;
    public javax.swing.JButton startTyping;
    public javax.swing.JButton stopTyping;
    public javax.swing.JTextArea textArea;
    // End of variables declaration
}
